import turtle
c = turtle.Pen()
c.pensize(3)
c.color('red')
c.circle(60)
c.left(72)
c.color('green')
c.circle(60)
c.left(72)
c.color('blue')
c.circle(60)
c.left(72)
c.color('yellow')
c.circle(60)
c.left(72)
c.color('purple')
c.circle(60)
c.left(72)
