import turtle
turt = turtle.Pen()
turt.pencolor('red')
turt.fillcolor('#004400')
turt.pensize(5)
turt.begin_fill()
turt.forward(200)
turt.left(90)
turt.forward(200)
turt.left(90)
turt.forward(200)
turt.left(90)
turt.forward(200)
turt.left(90)
turt.end_fill()
